service: deep-util-services
frameworkVersion: "=2.15.0"

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, "local"}
  region: us-east-1
  versionFunctions: false
  memorySize: 512 # in MB
  timeout: 30 # in seconds
  apiGateway:
    shouldStartNameWithService: true
  environment:
    IN_LAMBDA: true
    SERVICE: ${self:service}
    STAGE: ${self:provider.stage}
    SOURCE_TABLE_NAME: ${self:custom.sourceTableName}
    ASYNC_JOB_TABLE_NAME: ${self:custom.asyncJobTableName}
    CORS_DOMAIN: ${file(./secrets/${self:provider.stage}.json):CORS_DOMAIN}
    JWT_SECRET_OR_PUBLIC_KEY: ${file(./secrets/${self:provider.stage}.json):JWT_SECRET_OR_PUBLIC_KEY}
    MEDIA_BUCKET_NAME: ${file(./secrets/${self:provider.stage}.json):MEDIA_BUCKET_NAME}
    KMS_KEY_ID: ${file(./secrets/${self:provider.stage}.json):KMS_KEY_ID}
    MEDIA_BUCKET_ROOT: ${file(./secrets/${self:provider.stage}.json):MEDIA_BUCKET_ROOT}
    SENTRY_DNS: ${file(./secrets/${self:provider.stage}.json):SENTRY_DNS}
  iamRoleStatements:
    - Effect: Allow
      Sid: BucketAccess
      Action:
        - s3:ListBucket
        - s3:Head*
        - s3:Get*
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::${self:provider.environment.MEDIA_BUCKET_NAME}/*"
    - Effect: Allow
      Sid: KmsAccess
      Action:
        - kms:Decrypt
        - kms:DescribeKey
        - kms:Encrypt
        - kms:GenerateDataKey*
        - kms:ReEncrypt*
      Resource:
        - "arn:aws:kms:::key/{self:provider.environment.KMS_KEY_ID}"
    - Effect: Allow
      Sid: DynamdbAccess
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.SOURCE_TABLE_NAME}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.ASYNC_JOB_TABLE_NAME}"
    - Effect: Allow
      Action:
        # - lambda:InvokeFunction
        # - lambda:InvokeAsync
        - states:StartExecution
      # TODO: NOT WORKING Resource: ${self:resources.Outputs.SourceExtractStateMachine.Value}
      Resource: "*"

custom:
  stepFunctionConfig:
    beta:
      MaxConcurrency: 100
    nightly:
      MaxConcurrency: 200
    local:
      MaxConcurrency: 50
    MaxConcurrency: ${self:custom.stepFunctionConfig.${self:provider.stage}.MaxConcurrency, 1}
  dynamodbConfig:
    beta:
      BillingMode: PAY_PER_REQUEST
    dev:
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    nightly:
      BillingMode: PAY_PER_REQUEST
    local:
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      # ProvisionedThroughput:
      #   ReadCapacityUnits: 1
      #   WriteCapacityUnits: 1
    BillingMode: ${self:custom.dynamodbConfig.${self:provider.stage}.BillingMode, "PROVISIONED"}
    ProvisionedThroughput: ${self:custom.dynamodbConfig.${self:provider.stage}.ProvisionedThroughput}
  dynamodb:
    stages:
      - ${self:provider.stage}
  sourceTableName: "${self:service}-${self:provider.stage}-sources"
  asyncJobTableName: "${self:service}-${self:provider.stage}-async-jobs"
  authorizer: authorizerFunc
  cors:
    origin: ${self:provider.environment.CORS_DOMAIN}
  pythonRequirements:
    dockerizePip: true
    dockerFile: serverless-python-requirements/Dockerfile
    dockerExtraFiles:
      - /usr/lib64/libjpeg.so.62
    vendor: ./py-vendor
    useDownloadCache: false
    invalidateCaches: true
    noDeploy:
      # Dependencies of omitted packages must explicitly be omitted too
      - pytest
      - boto3
      - botocore
      - parameterized
  domains:
    beta: services.thedeep.io
    dev: services-alpha.thedeep.io
    nightly: services-nightly.thedeep.io
    local: services-local.thedeep.io
  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    stage: ${self:provider.stage}
    createRoute53Record: false
    certificateArn: ${file(./secrets/${self:provider.stage}.json):CERTIFICATE_ARN}

package:
  individually: false
  include:
    - "!./**"
    - "./src/**"
  exclude:
    - "**"

layers:
  headlessChrome:
    path: layers
    # path: layers/headless-chrome
    # Remove this when the bug is fixed https://github.com/serverless/serverless/issues/5892
    package:
      exclude:
        - "**"
      include:
        - "!**"
        - headless-chrome/**

functions:
  webInfoExtract:
    handler: src.functions.source_extract.handler.web_info_extract
    events:
      - http:
          path: web-info-extract
          method: get
          authorizer: ${self:custom.authorizer}
          cors: ${self:custom.cors}

  sourceExtract:
    handler: src.functions.source_extract.handler.main
    environment:
      SOURCE_EXTRACT_STATE_MACHINE_ARN: ${self:resources.Outputs.SourceExtractStateMachine.Value}
    events:
      - http:
          path: source-extract
          method: post
          authorizer: ${self:custom.authorizer}
          cors: ${self:custom.cors}
  sourceExtractJobSuccess:
    handler: src.functions.source_extract.handler.source_extract_job_success
  sourceExtractJobFailure:
    handler: src.functions.source_extract.handler.source_extract_job_failure
  sourceExtractJobTask:
    handler: src.functions.source_extract.handler.source_extract_job_mapped_task
    timeout: 300
  sourceExtractJobTaskFailure:
    handler: src.functions.source_extract.handler.source_extract_job_mapped_task_failure

  sourceThumbnailExtractJobTask:
    handler: src.functions.thumbnail_generator.handler.source_thumbnail_generator
    layers:
      - {Ref: HeadlessChromeLambdaLayer}
      - arn:aws:lambda:us-east-1:764866452798:layer:libreoffice-brotli:1
  sourceThumbnailExtractJobTaskFailure:
    handler: src.functions.thumbnail_generator.handler.source_thumbnail_extract_job_mapped_task_failure

  # TODO: Deploy without python dependencies
  authorizerFunc:
    runtime: nodejs12.x
    handler: src/authorizer/handler.auth

stepFunctions:
  stateMachines:
    SourceExtractStateMachine:
      name: "sourceExtractStateMachine-${self:provider.stage}"
      definition:
        StartAt: SourceExtractJob
        States:
          SourceExtractJob:
            Type: Map
            MaxConcurrency: ${self:custom.stepFunctionConfig.MaxConcurrency}
            ItemsPath: $.sources
            ResultPath: $.sources
            Catch:
              - ErrorEquals:
                - States.ALL
                ResultPath: $.error
                Next: SourceExtractJobFailure
            Next: SourceExtractJobSuccess
            Iterator:
              StartAt: SourceExtractJobTask
              States:
                SourceExtractJobTask:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [sourceExtractJobTask, Arn]
                  ResultPath: $.status
                  Catch:
                    - ErrorEquals:
                      - States.ALL
                      ResultPath: $.error
                      Next: SourceExtractJobTaskFailure
                  Next: SourceThumbnailExtractJobTask
                SourceThumbnailExtractJobTask:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [sourceThumbnailExtractJobTask, Arn]
                  ResultPath: $.status
                  End: true
                  Catch:
                    - ErrorEquals:
                      - States.ALL
                      ResultPath: $.error
                      Next: SourceThumbnailExtractJobTaskFailure
                SourceExtractJobTaskFailure:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [sourceExtractJobTaskFailure, Arn]
                  End: true
                  ResultPath: $.status
                SourceThumbnailExtractJobTaskFailure:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [sourceThumbnailExtractJobTaskFailure, Arn]
                  End: true
                  ResultPath: $.status
          SourceExtractJobSuccess:
            Type: Task
            Resource:
              Fn::GetAtt: [sourceExtractJobSuccess, Arn]
              End: true
            End: true
          SourceExtractJobFailure:
            Type: Task
            Resource:
              Fn::GetAtt: [sourceExtractJobFailure, Arn]
              End: true
            End: true

resources:
  Resources:
    AsyncJobTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        # Make sure to update PynamoDB models
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        BillingMode: ${self:custom.dynamodbConfig.BillingMode}
        ProvisionedThroughput: ${self:custom.dynamodbConfig.ProvisionedThroughput}
        TableName: ${self:custom.asyncJobTableName}
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
    SourceTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        # Make sure to update PynamoDB models
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        BillingMode: ${self:custom.dynamodbConfig.BillingMode}
        ProvisionedThroughput: ${self:custom.dynamodbConfig.ProvisionedThroughput}
        TableName: ${self:custom.sourceTableName}
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'${self:provider.environment.CORS_DOMAIN}'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        ResponseTemplates:
          application/json: ${file(./src/authorizer/error-template.txt)}
        RestApiId:
          Ref: "ApiGatewayRestApi"
    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'${self:provider.environment.CORS_DOMAIN}'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        ResponseTemplates:
          application/json: ${file(./src/authorizer/error-template.txt)}
        RestApiId:
          Ref: "ApiGatewayRestApi"
  Outputs:
    SourceExtractStateMachine:
      Description: The ARN of the source extraction state machine
      Value:
        Ref: "SourceExtractStateMachineDash${self:provider.stage}"

plugins:
  - serverless-domain-manager
  - serverless-python-requirements
  - serverless-plugin-include-dependencies
  - serverless-step-functions
  - serverless-dynamodb-local
  - serverless-offline  # always last
